import { alpha, createTheme } from '@mui/material/styles';

export const designTokens = {
  color: {
    brand: '#315f73', brandDark: '#244957', brandSubtle: '#edf4f6',
    canvas: '#f6f8f9', surface: '#ffffff', surfaceSubtle: '#f9fafb', surfaceSunken: '#f1f4f5',
    text: '#17252b', textSecondary: '#52636b', textMuted: '#718188',
    border: '#dde4e7', borderStrong: '#c5d0d5',
    healthy: '#287a5b', healthySubtle: '#edf7f2', healthyBorder: '#b9decf',
    atRisk: '#9a6715', atRiskSubtle: '#fff7e8', atRiskBorder: '#ead39f',
    critical: '#a33a3a', criticalSubtle: '#fff1f1', criticalBorder: '#e8bcbc',
    info: '#396b8c', infoSubtle: '#edf5fa', infoBorder: '#bdd5e4',
    neutral: '#66757c', neutralSubtle: '#f1f4f5', neutralBorder: '#d5dde0',
  },
  radius: { control: 7, card: 10, chip: 999 },
  border: { subtle: '1px solid #dde4e7', strong: '1px solid #c5d0d5' },
  shadow: { raised: '0 1px 2px rgba(23, 37, 43, 0.05), 0 1px 8px rgba(23, 37, 43, 0.025)', overlay: '0 12px 30px rgba(23, 37, 43, 0.12)' },
} as const;

const tone = (main: string, subtle: string, border: string, contrastText = main) => ({ main, subtle, border, contrastText });

export const theme = createTheme({
  palette: {
    mode: 'light',
    primary: { main: designTokens.color.brand, dark: designTokens.color.brandDark, light: designTokens.color.brandSubtle, contrastText: '#ffffff' },
    background: { default: designTokens.color.canvas, paper: designTokens.color.surface, subtle: designTokens.color.surfaceSubtle },
    surface: { default: designTokens.color.surface, elevated: designTokens.color.surface, sunken: designTokens.color.surfaceSunken },
    border: { subtle: designTokens.color.border, strong: designTokens.color.borderStrong },
    text: { primary: designTokens.color.text, secondary: designTokens.color.textSecondary, muted: designTokens.color.textMuted },
    divider: designTokens.color.border,
    status: {
      healthy: tone(designTokens.color.healthy, designTokens.color.healthySubtle, designTokens.color.healthyBorder),
      atRisk: tone(designTokens.color.atRisk, designTokens.color.atRiskSubtle, designTokens.color.atRiskBorder),
      critical: tone(designTokens.color.critical, designTokens.color.criticalSubtle, designTokens.color.criticalBorder),
      informational: tone(designTokens.color.info, designTokens.color.infoSubtle, designTokens.color.infoBorder),
      neutral: tone(designTokens.color.neutral, designTokens.color.neutralSubtle, designTokens.color.neutralBorder),
    },
    confidence: {
      high: tone(designTokens.color.healthy, designTokens.color.healthySubtle, designTokens.color.healthyBorder),
      medium: tone(designTokens.color.atRisk, designTokens.color.atRiskSubtle, designTokens.color.atRiskBorder),
      low: tone(designTokens.color.critical, designTokens.color.criticalSubtle, designTokens.color.criticalBorder),
      unknown: tone(designTokens.color.neutral, designTokens.color.neutralSubtle, designTokens.color.neutralBorder),
    },
  },
  spacing: 8,
  shape: { borderRadius: designTokens.radius.control },
  typography: {
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    h1: { fontSize: '1.75rem', lineHeight: 1.22, fontWeight: 680, letterSpacing: '-0.03em' },
    h2: { fontSize: '1.125rem', lineHeight: 1.4, fontWeight: 640, letterSpacing: '-0.012em' },
    h3: { fontSize: '1rem', lineHeight: 1.45, fontWeight: 620 },
    body1: { fontSize: '0.9375rem', lineHeight: 1.6 }, body2: { fontSize: '0.875rem', lineHeight: 1.55 },
    caption: { fontSize: '0.75rem', lineHeight: 1.5 },
    overline: { fontSize: '0.6875rem', lineHeight: 1.5, fontWeight: 700, letterSpacing: '0.08em' },
    button: { fontSize: '0.875rem', textTransform: 'none', fontWeight: 650, letterSpacing: 0 },
    pageEyebrow: { fontSize: '0.75rem', lineHeight: 1.5, fontWeight: 650, letterSpacing: '0.035em' },
    pageTitle: { fontSize: '1.75rem', lineHeight: 1.22, fontWeight: 680, letterSpacing: '-0.03em' },
    pageSubtitle: { fontSize: '0.9375rem', lineHeight: 1.65, fontWeight: 400 },
    sectionTitle: { fontSize: '1.0625rem', lineHeight: 1.4, fontWeight: 640, letterSpacing: '-0.012em' },
    cardTitle: { fontSize: '0.9375rem', lineHeight: 1.45, fontWeight: 620 },
    metricValue: { fontSize: '1.75rem', lineHeight: 1.15, fontWeight: 680, letterSpacing: '-0.035em' },
    metricLabel: { fontSize: '0.8125rem', lineHeight: 1.5, fontWeight: 500 },
    supporting: { fontSize: '0.8125rem', lineHeight: 1.55, fontWeight: 400 },
    metadata: { fontSize: '0.75rem', lineHeight: 1.5, fontWeight: 550, letterSpacing: '0.01em' },
  },
  components: {
    MuiCssBaseline: { styleOverrides: { body: { minWidth: 320 }, '::selection': { backgroundColor: alpha(designTokens.color.brand, 0.18) } } },
    MuiButtonBase: { styleOverrides: { root: { '&:focus-visible': { outline: `3px solid ${alpha(designTokens.color.brand, 0.28)}`, outlineOffset: 2 } } } },
    MuiButton: { defaultProps: { disableElevation: true }, styleOverrides: { root: { minHeight: 36, borderRadius: designTokens.radius.control }, contained: { boxShadow: 'none' } } },
    MuiCard: { defaultProps: { elevation: 0 }, styleOverrides: { root: { borderRadius: designTokens.radius.card, borderColor: designTokens.color.border } } },
    MuiPaper: { defaultProps: { elevation: 0 }, styleOverrides: { root: { backgroundImage: 'none' }, outlined: { borderColor: designTokens.color.border } } },
    MuiChip: { styleOverrides: { root: { borderRadius: designTokens.radius.chip, fontWeight: 650 }, sizeSmall: { height: 24, fontSize: '0.72rem' } } },
    MuiTooltip: { defaultProps: { arrow: true }, styleOverrides: { tooltip: { fontSize: '0.75rem', borderRadius: designTokens.radius.control, backgroundColor: designTokens.color.text } } },
    MuiDivider: { styleOverrides: { root: { borderColor: designTokens.color.border } } },
    MuiIconButton: { styleOverrides: { root: { borderRadius: designTokens.radius.control, '&:hover': { backgroundColor: designTokens.color.surfaceSunken } } } },
    MuiDrawer: { styleOverrides: { paper: { backgroundColor: designTokens.color.surfaceSubtle, borderColor: designTokens.color.border } } },
    MuiAppBar: { styleOverrides: { root: { backgroundColor: alpha(designTokens.color.surface, 0.96), color: designTokens.color.text } } },
    MuiListItemButton: { styleOverrides: { root: { '&.Mui-selected': { backgroundColor: designTokens.color.brandSubtle }, '&.Mui-disabled': { opacity: 0.48 } } } },
    MuiSkeleton: { styleOverrides: { root: { backgroundColor: designTokens.color.surfaceSunken } } },
    MuiAlert: { styleOverrides: { root: { borderRadius: designTokens.radius.card }, standardError: { backgroundColor: designTokens.color.criticalSubtle } } },
  },
});
